version = 1
SPDX-PackageName = "Robocodec"
SPDX-PackageSupplier = "ArcheBase Contributors"
SPDX-PackageDownloadLocation = "https://github.com/archebase/robocodec"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 ArcheBase"
SPDX-License-Identifier = "MulanPSL-2.0"
